spring:
  datasource:
    url: jdbc:h2:file:./data/demo
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update

  h2:
    console.path: /h2-console
    console.enabled: true
   # console.settings.trace: false
   # spring.h2.console.settings.web-allow-others: false
